disease(corona).
disease(influenza).
corona_is(disease).
influenza_is(disease).
symptomsD(fever,corona).
symptomsD(tiredness,corona).
symptomsD(cough,corona).
symptomsD(cough,influenza).
symptomsD(fever,influenza).
symptomsD(headaches,influenza).
types(corona,6).
diseaseT('229e',corona).
diseaseT(nl63,corona).
diseaseT(oc43,corona).
diseaseT(hku1,corona).
diseaseT(mers-cov,corona).
diseaseT(sars-cov,corona).
diseaseT(a,influenza).
diseaseT(b,influenza).
diseaseT(c,influenza).
diseaseT(d,influenza).
causeD(virus,corona).
causeD(virus,influenza).
symptomsOf(X):-symptomsD(Y,X),write(Y).
typesN(X):-types(X,Y),write(Y).
typesOf(X):-diseaseT(Y,X),write(Y).
causesOf(X):-causeD(Y,X),write(Y).
symptoms(X,Y,Z):-symptomsD(X,A),symptomsD(Y,A),symptomsD(Z,A),write(A).